### ISSUE TITLE
Spec field desription

### ISSUE THREAD

**Issue by artjoma** [itering/scale.go#12]
Could you please advice why needed Spec parameter:
` option := types.ScaleDecoderOption{Metadata: &m.Metadata, Spec: 0/1055/1058} `

and how Spec related to network/<network>.json ?

Thank you.

**Comment by freehere107** [comment]
Because the design is upgraded to the network runtime, the data structure changes. A specific version of struct is required during the codec process.
You can refer to
https://github.com/itering/scale.go/blob/ac2a99dc5b11b891d90325a27515a9bc6e1b1a63/network/kusama.json#L220
