### ISSUE TITLE
panic: Not find Extrinsic Lookup 7cdc, please check metadata info w/ Polkadot block 4113389

### ISSUE THREAD

**Issue by gavinbd** [itering/scale.go#19]
What causes this issue?

Im loading the metadata at startup:

```
var metadata string
client.CallFor(appctx.Context(), &metadata, "state_getMetadata")
m := scalecodec.MetadataDecoder{}
m.Init(utiles.HexToBytes(metadata))
err := m.Process()
if err != nil {
    return nil, err
}
```

Loading custom types based on the hex encoded value of https://github.com/itering/scale.go/blob/master/network/polkadot.json

```
// Register custom types for the network
cc, err := hex.DecodeString('bytes')
if err != nil {
    return nil, err
}
types.RegCustomTypes(source.LoadTypeRegistry(cc))
```

Seeing a similar error on block 3006321

```
panic: Not find Extrinsic Lookup 1303, please check metadata info
```

Is this coming from an outdated custom types file? If so where do i get this data from?

**Comment by gavinbd** [comment]
I can see there was a similar issue here: https://github.com/itering/scale.go/issues/14

But im not sure how to get the latest block spec?

**Comment by freehere107** [comment]
@gavinbd You may reference https://github.com/itering/scale.go/blob/615304dfc82a6ba95546d2053d850d06ff4a0b53/extrinsic_test.go#L33

with spec 28, just like

```
 option := types.ScaleDecoderOption{Metadata: &m.Metadata, Spec: 28} 
```

**Comment by gavinbd** [comment]
That simple :D

Does the spec correspond to the release version numbering: https://github.com/paritytech/polkadot/releases

**Comment by gavinbd** [comment]
I get the below error when using spec 28. Am i missing another setup step? 

It gets much further when not specifying a spec number

```
Getting block 3000003
panic: runtime error: index out of range [18] with length 5

goroutine 1 [running]:
github.com/itering/scale.go/types.(*Enum).Process(0xc00024e640)
        /Users/gavinwoods/go/pkg/mod/github.com/itering/scale.go@v1.0.6/types/types.go:290 +0x87f

```

**Comment by gavinbd** [comment]
I think i found the issue. I need the get the runtime version for that specific block:

```
var r Runtime
	err = c.RPC.CallFor(appctx.Context(), &r, "chain_getRuntimeVersion", hash)
	if err != nil {
		return nil, err
	}
```

And feed the specVersion into the decoder. Hopefully this helps someone else in the future. But ill close this now
