### ISSUE TITLE
Panic processing batch_all extrinsic for Polkadot block 4230783

### ISSUE THREAD

**Issue by gavinbd** [itering/scale.go#21]
Im getting the following error when parsing the titled block:

```
runtime error: index out of range [7] with length 5
/usr/local/go/src/runtime/panic.go:88 (0x403ef64)
        goPanicIndex: panic(boundsError{x: int64(x), signed: true, y: y, code: boundsIndex})
/Users/gavinwoods/go/pkg/mod/github.com/itering/scale.go@v1.0.11/types/types.go:290 (0x4b8cc3e)
        (*Enum).Process: if subType := e.TypeMapping.Types[e.Index]; subType != "" 
```
The issue lies at processing the type: "Address" at offsetStart 353

```
if subType := e.TypeMapping.Types[e.Index]; subType != "" {
			e.Value = map[string]interface{}{e.TypeMapping.Names[e.Index]: e.ProcessAndUpdateData(subType)}
			return
		}
``` 
It tries to access index 7 when there only 5 types for this in spec 28

I believe its related to the batch all extrinsic which I havent encountered before but im not sure what custom type I am missing from the config. Is there a guide somewhere to figuring these issues out?

**Comment by freehere107** [comment]
I guess it’s because this is not defined, you can give it a try

```
  "Keys#28-?": {
    "type": "struct",
    "type_mapping": [
      [
        "grandpa",
        "AccountId"
      ],
      [
        "babe",
        "AccountId"
      ],
      [
        "im_online",
        "AccountId"
      ],
      [
        "para_validator",
        "AccountId"
      ],
      [
        "para_assignment",
        "AccountId"
      ],
      [
        "authority_discovery",
        "AccountId"
      ]
    ]
  }
```

**Comment by gavinbd** [comment]
That was it. Thanks. Is there a place where you gather this information so in future I could make some PR's for the polkadot networks file.

**Comment by freehere107** [comment]
Here you can see some published information https://github.com/paritytech/polkadot/releases
