### ISSUE TITLE
Decoder mem leak

### ISSUE THREAD

**Issue by artjoma** [itering/scale.go#37]
`watch -n 5 ps v <PID>`

Start:
TRS  DRS     RSS    %MEM
4031 1525220 24284  0.0

End:
TRS  DRS     RSS    %MEM
4031 2081068 487960  1.5

Memory usage growing till OS memory free space limit. Short test:

```
func TestDecodeMetaBulk(t *testing.T) {
	blockMetadata := "0x6d6574610d781853797374656d011853797374656d401...1746541747465737473"

	for i:=0; i < 10_000; i++ {
		m := scalecodec.MetadataDecoder{}
		m.Init(utiles.HexToBytes(blockMetadata))
		if err := m.Process(); err != nil {
			panic(err)
		}
		if i % 100 == 0 {
			fmt.Println(i)
			debug.FreeOSMemory()
		}
	}
	fmt.Println("End")
}
```

**Comment by freehere107** [comment]
Thank you feedback， I will fix it as soon as possible

**Comment by freehere107** [comment]
@artjoma This issue has been fixed , thank you feedback
