### ISSUE TITLE
How to parse OpaqueCall value?

### ISSUE THREAD

**Issue by crossle** [itering/scale.go#46]
<img width="727" alt="Screen Shot 2021-11-04 at 23 10 41" src="https://user-images.githubusercontent.com/1675131/140341208-0544106d-38bb-4492-a379-a7eec522df8c.png">

**Comment by freehere107** [comment]
```
m := types.ScaleDecoder{}
m.Init(types.ScaleBytes{Data: util.HexToBytes(raw)}, types.ScaleDecoderOption{Metadata:Metadata})
m.ProcessAndUpdateData("OpaqueCall")
```

**Comment by crossle** [comment]
> ```
> m := types.ScaleDecoder{}
> m.Init(types.ScaleBytes{Data: util.HexToBytes(raw)}, types.ScaleDecoderOption{Metadata:Metadata})
> m.ProcessAndUpdateData("OpaqueCall")
> ```

get empty data.  map[call_index: call_module: call_name: params:[]]

**Comment by freehere107** [comment]
@crossle Can you paste you code?

**Comment by crossle** [comment]
```
				m := types.ScaleDecoder{}
				m.Init(types.ScaleBytes{Data: util.HexToBytes("05000061d0f165cc77b059f1ac1fe2598cd90f487ab60dc26c63d7633852d554ad1db50700e40b5402")}, &types.ScaleDecoderOption{Metadata: metadataRaw})
				a := m.ProcessAndUpdateData("OpaqueCall")
```
metadata raw from state_getMetadata on the block 7329637

**Comment by freehere107** [comment]
@crossle  ok, this type is ``Call``
you can use this ``m.ProcessAndUpdateData("Call")``

**Comment by crossle** [comment]
Got it, Thanks.
