### ISSUE TITLE
DecodeExtrinsic error on runtime 26

### ISSUE THREAD

**Issue by crossle** [itering/scale.go#5]
Recovering from panic in DecodeExtrinsic error is: Not find Extrinsic Lookup 0a00, please check metadata info

**Comment by freehere107** [comment]
please check weight type, maybe set u64 can fix it

**Comment by crossle** [comment]
Weight is `  "Weight": "u64", `

**Comment by freehere107** [comment]
> Weight is ` "Weight": "u64",`, I found the decode the block 2436698 will have the error.

@crossle  oh, I know why, you can notice that this block is a runtime upgrade, it needs to use the previous version of metadata

**Comment by crossle** [comment]
> @crossle oh, I know why, you can notice that this block is a runtime upgrade, it needs to use the previous version of metadata

YES, it's the runtime upgrade. Thanks, I just ignore the error.
