### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-5251222233895927662] [recovered]

### ISSUE THREAD

**Issue by raojianli** [itering/scale.go#51]
--- FAIL: TestClient_TestDemo (0.00s)
panic: runtime error: slice bounds out of range [:-5251222233895927662] [recovered]
	panic: runtime error: slice bounds out of range [:-5251222233895927662]

goroutine 66 [running]:
testing.tRunner.func1.2(0x43e4360, 0xc00027ad68)
	/usr/local/go/src/testing/testing.go:1143 +0x332
testing.tRunner.func1(0xc000182a80)
	/usr/local/go/src/testing/testing.go:1146 +0x4b6
panic(0x43e4360, 0xc00027ad68)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/itering/scale.go/types.(*ScaleBytes).GetNextBytes(...)
	/Users/abel/go/pkg/mod/github.com/itering/scale.go@v1.1.42/types/scaleBytes.go:18
github.com/itering/scale.go/types.(*ScaleDecoder).NextBytes(0xc0000f65a0, 0xb71fe93350000008, 0xc, 0x4391f40, 0xc0002b0638)

**Comment by freehere107** [comment]
Please provide the source code of TestDemo @raojianli
