### ISSUE TITLE
panic: Not found decoder class *classType* in goroutines

### ISSUE THREAD

**Issue by UnicornIdeas** [itering/scale.go#53]
I am trying to implement a decoder for Header and Extrinsics, when I use a single routine it works perfectly for millions of packages, but when I try to use more goroutines it panics after the second decoder starts. It seems that the decoder returns nil decoding class.

Error:

```
panic: Not found decoder class Header

goroutine 23 [running]:
github.com/itering/scale.go/types.(*ScaleDecoder).ProcessAndUpdateData(0xc00004de58, {0xd119bf, 0x6})
        /go/pkg/mod/github.com/itering/scale.go@v1.1.49/types/base.go:130 +0x788
exit status 2
```

**Comment by freehere107** [comment]
@UnicornIdeas Have you registered the ``Header`` type?

**Comment by UnicornIdeas** [comment]
> @UnicornIdeas Have you registered the `Header` type?

I did not, but when it is a single routine the decoder knows how to decode the data, shouldn't I get an error everytime if the Header type does not exist?

**Comment by mrcxm** [comment]
> @UnicornIdeas Have you registered the `Header` type?

Do you know how can I decode the block header? I cannot find the class and I tried to implement the schema but with no success.

This is what I tried to do:
```
{
  "Digest":{
	"type_mapping":[
		[
		    "logs",
		    "Vec<LogsData>"
		]
	],
	"type": "struct"
},
"LogsData":{
	"type_mapping":[
		[
		    "data",
		    "HexBytes"
		],
		[
		    "engine",
		    "U32"
		]
	],
	"type": "struct"
   },
  "Unicorn": {
  "type": "struct",
  "type_mapping": [
    [
      "digest",
      "Digest"
    ],
    [
      "extrinsics_root",
      "H256"
    ],
    [
      "number",
      "BlockNumber"
    ],
    [
      "parent_hash",
      "H256"
    ],
    [
      "state_root",
      "H256"
    ]
  ]
}
}
```

And this is how the header digest is structured, I think there is the problem with my class.

```
"digest":
map[
    "logs": [
        map[
            "PreRuntime":map[
                "data": 0x010000000093decc0f00000000362ed8d6055645487fe42e9c8640be651f70a3a2a03658046b2b43f021665704501af9b1ca6e974c257e3d26609b5f68b5b0a1da53f7f252bbe5d94948c39705c98ffa4b869dd44ac29528e3723d619cc7edf1d3f7b7a57a957f6a7e9bdb270a,
                "engine": 1161969986
            ]
        ] 
        map[Consensus:map[
                "data":0118fa3437b10f6e7af8f31362df3a179b991a8c56313d1bcd6307a4d0c734c1ae310100000000000000d2419bc8835493ac89eb09d5985281f5dff4bc6c7a7ea988fd23af05f301580a0100000000000000ccb6bef60defc30724545d57440394ed1c71ea7ee6d880ed0e79871a05b5e40601000000000000005e67b64cf07d4d258a47df63835121423551712844f5b67de68e36bb9a21e12701000000000000006236877b05370265640c133fec07e64d7ca823db1dc56f2d3584b3d7c0f1615801000000000000006c52d02d95c30aa567fda284acf25025ca7470f0b0c516ddf94475a1807c4d2501000000000000000000000000000000000000000000000000000000000000000000000000000000,
                "engine": 1161969986
            ]
        ] 
        map[
            "Seal":map[
                "data": 0xd468680c844b19194d4dfbdc6697a35bf2b494bda2c5a6961d4d4eacfbf74574379ba0d97b5bb650c2e8670a63791a727943bcb699dc7a228bdb9e0a98c9d089,
                "engine": 1161969986
            ]
        ]
    ]
]
```

**Comment by freehere107** [comment]
@UnicornIdeas Can you give me an example, what data are you going to decode?

**Comment by UnicornIdeas** [comment]
> @UnicornIdeas Can you give me an example, what data are you going to decode?

I am trying to decode polkadot block header, to extract logs, but the raw header data is extracted from rocksdb and has the following structure:

`map[digest:map[logs:[map[type:PreRuntime value:map[data:0x010000000093decc0f00000000362ed8d6055645487fe42e9c8640be651f70a3a2a03658046b2b43f021665704501af9b1ca6e974c257e3d26609b5f68b5b0a1da53f7f252bbe5d94948c39705c98ffa4b869dd44ac29528e3723d619cc7edf1d3f7b7a57a957f6a7e9bdb270a engine:1161969986]] map[type:Consensus value:map[data:0118fa3437b10f6e7af8f31362df3a179b991a8c56313d1bcd6307a4d0c734c1ae310100000000000000d2419bc8835493ac89eb09d5985281f5dff4bc6c7a7ea988fd23af05f301580a0100000000000000ccb6bef60defc30724545d57440394ed1c71ea7ee6d880ed0e79871a05b5e40601000000000000005e67b64cf07d4d258a47df63835121423551712844f5b67de68e36bb9a21e12701000000000000006236877b05370265640c133fec07e64d7ca823db1dc56f2d3584b3d7c0f1615801000000000000006c52d02d95c30aa567fda284acf25025ca7470f0b0c516ddf94475a1807c4d2501000000000000000000000000000000000000000000000000000000000000000000000000000000 engine:1161969986]] map[type:Seal value:map[data:0xd468680c844b19194d4dfbdc6697a35bf2b494bda2c5a6961d4d4eacfbf74574379ba0d97b5bb650c2e8670a63791a727943bcb699dc7a228bdb9e0a98c9d089 engine:1161969986]]]] extrinsics_root:0x9a87f6af64ef97aff2d31bebfdd59f8fe2ef6019278b634b2515a38f1c4c2420 number:1 parent_hash:0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3 state_root:0xc56fcd6e7a757926ace3e1ecff9b4010fc78b90d459202a339266a7f6360002f]`

This is just an example, the logs structure can be different, not all maps present (PreRuntime, Consensus, Seal) or even more, so the structure is variable.

**Comment by UnicornIdeas** [comment]
> @UnicornIdeas Can you give me an example, what data are you going to decode?

Or if you are talking about the raw data, this is the string I am trying to decode:
```

rawHeader := `91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c304c56fcd6e7a757926ace3e1ecff9b4010fc78b90d459202a339266a7f6360002f9a87f6af64ef97aff2d31bebfdd59f8fe2ef6019278b634b2515a38f1c4c24200c0642414245b501010000000093decc0f00000000362ed8d6055645487fe42e9c8640be651f70a3a2a03658046b2b43f021665704501af9b1ca6e974c257e3d26609b5f68b5b0a1da53f7f252bbe5d94948c39705c98ffa4b869dd44ac29528e3723d619cc7edf1d3f7b7a57a957f6a7e9bdb270a044241424549040118fa3437b10f6e7af8f31362df3a179b991a8c56313d1bcd6307a4d0c734c1ae310100000000000000d2419bc8835493ac89eb09d5985281f5dff4bc6c7a7ea988fd23af05f301580a0100000000000000ccb6bef60defc30724545d57440394ed1c71ea7ee6d880ed0e79871a05b5e40601000000000000005e67b64cf07d4d258a47df63835121423551712844f5b67de68e36bb9a21e12701000000000000006236877b05370265640c133fec07e64d7ca823db1dc56f2d3584b3d7c0f1615801000000000000006c52d02d95c30aa567fda284acf25025ca7470f0b0c516ddf94475a1807c4d250100000000000000000000000000000000000000000000000000000000000000000000000000000005424142450101d468680c844b19194d4dfbdc6697a35bf2b494bda2c5a6961d4d4eacfbf74574379ba0d97b5bb650c2e8670a63791a727943bcb699dc7a228bdb9e0a98c9d089`
rawData := utiles.HexToBytes(rawHeader)
```

**Comment by freehere107** [comment]
@UnicornIdeas ok, The ``rawHeader`` data is obtained through which rpc? Can you provide specific information?

**Comment by helmealex** [comment]
The raw header is obtained directly from the rocksdb database. It is the scale encoded header structure

**Comment by freehere107** [comment]
@helmealex 

try this code

```
m := types.ScaleDecoder{}
m.Init(types.ScaleBytes{Data: raw}, nil)
value := m.ProcessAndUpdateData("Header")
```

**Comment by UnicornIdeas** [comment]
> @helmealex
> 
> try this code
> 
> ```
> m := types.ScaleDecoder{}
> m.Init(types.ScaleBytes{Data: raw}, nil)
> value := m.ProcessAndUpdateData("Header")
> ```
> 
> and it will be return like this
> 
> ```
> {
>   "digest": {
>     "logs": [
>       {
>         "PreRuntime": {
>           "data": "0x010000000093decc0f00000000362ed8d6055645487fe42e9c8640be651f70a3a2a03658046b2b43f021665704501af9b1ca6e974c257e3d26609b5f68b5b0a1da53f7f252bbe5d94948c39705c98ffa4b869dd44ac29528e3723d619cc7edf1d3f7b7a57a957f6a7e9bdb270a",
>           "engine": 1161969986
>         }
>       },
>       {
>         "Consensus": {
>           "data": "0118fa3437b10f6e7af8f31362df3a179b991a8c56313d1bcd6307a4d0c734c1ae310100000000000000d2419bc8835493ac89eb09d5985281f5dff4bc6c7a7ea988fd23af05f301580a0100000000000000ccb6bef60defc30724545d57440394ed1c71ea7ee6d880ed0e79871a05b5e40601000000000000005e67b64cf07d4d258a47df63835121423551712844f5b67de68e36bb9a21e12701000000000000006236877b05370265640c133fec07e64d7ca823db1dc56f2d3584b3d7c0f1615801000000000000006c52d02d95c30aa567fda284acf25025ca7470f0b0c516ddf94475a1807c4d2501000000000000000000000000000000000000000000000000000000000000000000000000000000",
>           "engine": 1161969986
>         }
>       },
>       {
>         "Seal": {
>           "data": "0xd468680c844b19194d4dfbdc6697a35bf2b494bda2c5a6961d4d4eacfbf74574379ba0d97b5bb650c2e8670a63791a727943bcb699dc7a228bdb9e0a98c9d089",
>           "engine": 1161969986
>         }
>       }
>     ]
>   },
>   "extrinsics_root": "0x9a87f6af64ef97aff2d31bebfdd59f8fe2ef6019278b634b2515a38f1c4c2420",
>   "number": 1,
>   "parent_hash": "0x91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3",
>   "state_root": "0xc56fcd6e7a757926ace3e1ecff9b4010fc78b90d459202a339266a7f6360002f"
> }
> ```

That is the way we decoded data from Header, but the problem was it worked only for one scaleDecoder, if we spawned several go routines, each with its own decoder, then that error  with "cannot find class Header" appeared. The solution was to load schema from polkadot file before starting to spawn routines and use multiple decoders in parallel. 

The issue is resolved so I will close it now, thanks for your help!
