### ISSUE TITLE
Vec length exceeded error

### ISSUE THREAD

**Issue by helmealex** [itering/scale.go#54]
![vec_length](https://user-images.githubusercontent.com/83425570/161627797-2b65b8cf-8d53-4012-aff5-28b8eeb37264.jpeg)

Vec length 1003898 exceeds 50000 with subType AccountId

**Comment by freehere107** [comment]
@helmealex Please provide an example case?

**Comment by UnicornIdeas** [comment]
Managed to reproduce the bug. `Failed to decode extrinsic for block 203535: [Recovering from panic in DecodeExtrinsic error is: Vec length 1003898 exceeds 50000 with subType AccountId `. The failing block is the block number 203535.

**Comment by freehere107** [comment]
which network is raised this issue?

**Comment by helmealex** [comment]
The problem is on polkadot

**Comment by freehere107** [comment]
Did you pass in https://github.com/itering/scale.go/blob/master/types/base.go#L59 this parameter, Polkadot has some structural changes in the runtime upgrade

**Comment by helmealex** [comment]
bodyDecoder.Init(types.ScaleBytes{Data: rawBodyData}, nil)

**Comment by freehere107** [comment]
@helmealex You can reference this https://github.com/itering/scale.go/blob/master/extrinsic_test.go#L24

**Comment by helmealex** [comment]
I will give it a try. Thanks!

**Comment by helmealex** [comment]
Actually I used `decodedExtrinsics, err := substrate.DecodeExtrinsic(rawExtrinsicList, metadataInstant, specVersion)` and that error happened. https://github.com/itering/substrate-api-rpc/blob/master/extrinsic.go#L14 already uses what you suggested

**Comment by helmealex** [comment]
Cloned your repo locally and removed the limit from https://github.com/itering/scale.go/blob/master/types/types.go#L210 and it worked

**Comment by helmealex** [comment]
@freehere107 can you give me please any updates regarding this issue? Thank you!
