### ISSUE TITLE
Support related questions

### ISSUE THREAD

**Issue by ChinmayPatel** [itering/scale.go#6]
Does it support;

- V12 Metadata?
- ability to read utility batch extrinsic? 
- ability to parse Remarks as part of a utility batch extrinsic?

Lastly, where can I find the usage docs?

**Comment by freehere107** [comment]
@ChinmayPatel hello, it supports V12 Metadata
you can find some example here https://github.com/itering/substrate-api-rpc and https://github.com/itering/subscan-essentials

**Comment by ChinmayPatel** [comment]
... and how about 

ability to read utility batch extrinsic?
ability to parse Remarks as part of a utility batch extrinsic?

**Comment by freehere107** [comment]
ability to read utility batch extrinsic?
**of course, you just decode like normal extrinsic, like https://westend.subscan.io/extrinsic/3443522-1**

ability to parse Remarks as part of a utility batch extrinsic?

**part of extrinsic you need parse metadata get relate doc**

**Comment by ChinmayPatel** [comment]
This is fantastic. I'll go through Subscan's code to understand how you parsed the information. 

Thanks for the info.
