### ISSUE TITLE
Panic `Vec length` on decoding events from `Moonbase Alpha`

### ISSUE THREAD

**Issue by m0ssc0de** [itering/scale.go#61]
Hello scale.go teams. I need your help. Please help me to find out why this panic occurred or guide me to research. Thanks.

We got a panic `panic: Vec length 678189135 exceeds 50000 with subType Hash`, when processing events from block 946237 on Moonbase Alpha network. The proof scripts was placed https://github.com/m0ssc0de/scale-demo/tree/main/onlyScale with prepared raw data got from rocksdb. That git repo also contain how to get the raw data.

Thanks your nice project!

**Comment by freehere107** [comment]
@m0ssc0de You can use this types json https://github.com/itering/scale.go/blob/master/network/moonbase.json

**Comment by m0ssc0de** [comment]
Sorry again. We face a similar problem at 2,706,909 . More details will be collected later. Do you have some update on https://github.com/itering/scale.go/blob/master/network/moonbase.json ?
