### ISSUE TITLE
types for substrate v4.0

### ISSUE THREAD

**Issue by andropixels** [itering/scale.go#62]
do i need to upgrade the version of scale for substrate v4.0 chain?

**Comment by freehere107** [comment]
@andropixels no need.

**Comment by andropixels** [comment]
but substrate v4.0 does not need type registry right ? then how block explorer will work for substrate v4.0?

**Comment by freehere107** [comment]
@andropixels  substrate v4.0 is Metadata v14, it will auto reg type registry. let's discuss it here https://github.com/subscan-explorer/subscan-essentials/issues/200
