### ISSUE TITLE
Question: How to decode/process a block?

### ISSUE THREAD

**Issue by ChinmayPatel** [itering/scale.go#7]
# Problem
I'm trying to decode the block retrieved using the `rpc.ChainGetBlock`, but unable to find proper example or documentation on how to do it. 

Logically, I should; 
1. Set the RPC endpoint
2. get the metadata at the given block for accuracy
3. get the block data & parse it
4. get the extrinsic data and parse it

I'm struggling on the 3rd step -- mostly my lack of knowledge in Golang.

# Code 
```
package main

import (
	"fmt"

	// "github.com/itering/substrate-api-rpc"
	"github.com/itering/scale.go"
	"github.com/itering/scale.go/utiles"
	"github.com/itering/substrate-api-rpc/rpc"
	"github.com/itering/substrate-api-rpc/websocket"
	"github.com/itering/scale.go/types"
)

func main(){
	websocket.SetEndpoint("wss://westend-rpc.polkadot.io")
	fmt.Println("Starting the example.")

	blockHash := "0x39718cb67ed41fb088ecfa3b7e5fe775d6b4867b38f67bc5be291b36ede18d8b";
	metadata, _ := rpc.GetMetadataByHash(nil, blockHash);
	newMetadata := utiles.HexToBytes(metadata)

	m := scalecodec.MetadataDecoder{};
	m.Init(newMetadata);
	m.Process();


	block :=	rpc.ChainGetBlock(0, blockHash);
	// What should I use here to decode the block before passing the extrinsic to the Extrinsic Decoder?
	// Feel free to share the code snippets or the example from the `subtrate-essentials` repo

	e := scalecodec.ExtrinsicDecoder{}
	option := types.ScaleDecoderOption{Metadata: &m.Metadata}
	e.Init(types.ScaleBytes{Data: block}, &option)
	e.Process();

	// substrate.DecodeEvent(block);
	fmt.Println("BlockData", e);

}
```

# Solution
What should I do to decode the block before passing the extrinsic to the Extrinsic Decoder? Feel free to share the code snippets or the example from the `subtrate-essentials` repo.

**Comment by freehere107** [comment]
You can refer to the code here
https://github.com/itering/subscan-essentials/blob/419d6773495fad14138d2831eecd97025e1b3cef/internal/service/substrate.go#L189

**Comment by ChinmayPatel** [comment]
This has worked. Thanks for the link. I was able to follow the example pretty clearly. If you have examples for  listening to the blocks (other than https://github.com/itering/subscan-essentials/blob/31cf7bf7ecafcd719c321803b2ca29e9fe644eca/internal/observer/observer.go ) I'll take that info, too. 

Thanks again!
