### ISSUE TITLE
How to decode a custom type 

### ISSUE THREAD

**Issue by nuel77** [itering/scale.go#75]
Hello, i have a custom type 
```json
{
  "AssetId": {
      "_enum": [
        {
          "asset": "u128"
        },
        {
          "native": null
        }
      ]
    },
    "TradingPair": {
      "base_asset": "AssetId",
      "quote_asset": "AssetId"
    }
  }
  ```
  I am encoding this using scale in rust and calling a server written in go. The data comes as scale-encoded bytes. How can I decode these bytes back to the original type in go?

**Comment by freehere107** [comment]
@nuel77 You can use this tool https://github.com/itering/scale.go/blob/master/convert.py
