### ISSUE TITLE
Bad transction payload with hexadecimal parameter

### ISSUE THREAD

**Issue by MarcoOl94** [itering/scale.go#84]
Hi, I've created a custom blockchain using the substrate framework, in particular, I've added a custom transaction that takes as input a hexadecimal string.
The problem is that when I build the transaction payload I see that there is a "0x" inside which it shouldn't be present.

E.g.
	`signedTransaction, err := client.SignTransaction("myModule", "myTx", "0x1592b150....")`
        
The payload generated by the function **EncodeWithOpt** is this `32020x1592b150.....`

I found a workaround by changing this [line](https://github.com/itering/scale.go/blob/master/types/base.go#L214) with `return utiles.TrimHex(out[0].String())`.

Am I missing something or is there a better way to do this?

Thanks!

**Comment by freehere107** [comment]
@MarcoOl94 This issue has been fixed. Please use latest verison
