### ISSUE TITLE
`FixedU8` codec not matched for `[4;u8]`

### ISSUE THREAD

**Issue by kziemianek** [itering/scale.go#85]
First of all, thank you for this project, it really helps me glue golang app with rpc endpoint consuming scale encoded values.

What I've found so far is that it really makes difference whether `[4;u8]` or `[4; u8]` type is used for encoding.

How currently types and codecs are correlated:
`[4;u8]` -> `FixedArray` 
`[4; u8]` -> `FixedU8`

Encoding implication:
`[4;u8]` -> `types.Encode("[u8;4]", []byte{2, 2, 2, 2})` -> `3032303230323032`
`[4; u8]` -> `types.Encode("[u8; 4]", []byte{2, 2, 2, 2})` -> `02020202` 

How I would expect it to be:
`[4;u8]` -> `FixedU8` 
`[4; u8]` -> `FixedU8`

**Comment by freehere107** [comment]
@kziemianek Can you provide test code? I can't reproduce it at the moment

**Comment by kziemianek** [comment]
@freehere107 actually it works a little bit different than I described - in second case I need to pass hex encoded string because if byte slice is passed then it panics. 

```
	byteArr := []byte{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
	encoded := types.Encode("[u8;16]", byteArr)
	fmt.Println(encoded)

result:
00000000000000000000000000000000
```

```
	byteArr := []byte{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
	encoded := types.Encode("[u8; 16]", byteArr)
	fmt.Println(encoded)
result:
panic: reflect: Call using []uint8 as type string
```

```
	byteArr := []byte{2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2}
	encoded := types.Encode("[u8; 16]", utiles.BytesToHex(byteArr))
	fmt.Println(encoded)
result:
02020202020202020202020202020202
```

`[u8;4]` and `[u8; 4]` are almost equal, there is only space after the semicolon. From my understanding this space should be irrelevant but it turns out it has huge impact.

**Comment by freehere107** [comment]
@kziemianek Make sense. Thanks for you feedback. I will update it as soon.

**Comment by freehere107** [comment]
@kziemianek This issue has been fixed.
