### ISSUE TITLE
Support types StakingPagedExposureMetadata and StakingExposurePage

### ISSUE THREAD

**Issue by pacmessica** [itering/scale.go#88]
`types/registry.go` is missing [SpStakingPagedExposureMetadata](https://github.com/polkadot-js/api/blob/e0e9829417763f56afd58a27a4bae77058a6a1d7/packages/types-augment/src/lookup/types-substrate.ts#L7030) and [SpStakingExposurePage](https://github.com/polkadot-js/api/blob/e0e9829417763f56afd58a27a4bae77058a6a1d7/packages/types-augment/src/lookup/types-substrate.ts#L7038C13-L7038C34).

Just need this commit from as far as I can tell. https://github.com/pacmessica/scale.go/commit/e30daa0a255c53f0a71b1b5d599eccbfb5799a6e

**Comment by freehere107** [comment]
@pacmessica Types has auto registered by runtime metadata.

**Comment by pacmessica** [comment]
great!

How do I get the name of the type? Example, if I try `ProcessAndUpdateData("StakingExposurePage")` I get a panic: `Not found decoder class StakingExposurePage`.

**Comment by freehere107** [comment]
@pacmessica This type name is ``sp_staking:ExposurePage``.You may need to check this https://polkadot.subscan.io/runtime/Staking?version=1002000

<img width="1309" alt="image" src="https://github.com/itering/scale.go/assets/7080674/54626972-e2b8-4186-be8e-45a3e7004e85">
